local nhl_teams = {}

nhl_teams.ANA = {
	name = "Anaheim Ducks",
	abbreviation = "ANA",
	logo = "rbxassetid://472756010",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9300257360",
			},
			pants = {
				"rbxassetid://9300405569",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9300319590",
			},
			pants = {
				"rbxassetid://9300405569",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#C4471E"),
		auxillary = Color3.fromHex("#B9975B"),
		tertiary = Color3.fromHex("#000000"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.DAL = {
	name = "Dallas Stars",
	abbreviation = "DAL",
	logo = "rbxassetid://474186100",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://16949810851",
			},
			pants = {
				"rbxassetid://454831482",
			},
		},

		away = {
			jersey = {
				"rbxassetid://16949810851",
			},
			pants = {
				"rbxassetid://6401728849",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#006847"),
		auxillary = Color3.fromHex("#8F8F8C"),
		tertiary = Color3.fromHex("#000000"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.SJS = {
	name = "San Jose Sharks",
	abbreviation = "SJS",
	logo = "rbxassetid://474197824",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432246671",
			},
			pants = {
				"rbxassetid://9432248267",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432248058",
			},
			pants = {
				"rbxassetid://9432248267",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#1a5661"),
		auxillary = Color3.fromHex("#ffffff"),
		tertiary = Color3.fromHex("#000000"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.MTL = {
	name = "Montreal Canadiens",
	abbreviation = "MTL",
	logo = "rbxassetid://7043213058",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432145914",
			},
			pants = {
				"rbxassetid://9432146153",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432149858",
			},
			pants = {
				"rbxassetid://9432149892",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#AF1E2D"),
		auxillary = Color3.fromHex("#192168"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.LAK = {
	name = "Los Angeles Kings",
	abbreviation = "LAK",
	logo = "rbxassetid://474188417",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9392361705",
			},
			pants = {
				"rbxassetid://9432104645",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432118509",
			},
			pants = {
				"rbxassetid://9432120232",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#111111"),
		auxillary = Color3.fromHex("#A2AAAD"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.DET = {
	name = "Detroit Red Wings",
	abbreviation = "DET",
	logo = "rbxassetid://474186465",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9392298651",
			},
			pants = {
				"rbxassetid://9392298828",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9392307211",
			},
			pants = {
				"rbxassetid://9392307449",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#ce1126"),
		auxillary = Color3.fromHex("#ffffff"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.TOR = {
	name = "Toronto Maple Leafs",
	abbreviation = "TOR",
	logo = "rbxassetid://474199408",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432360346",
			},
			pants = {
				"rbxassetid://9432360499",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432361672",
			},
			pants = {
				"rbxassetid://9432361794",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#121b86"),
		auxillary = Color3.fromHex("#ffffff"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.BUF = {
	name = "Buffalo Sabres",
	abbreviation = "BUF",
	logo = "rbxassetid://472762979",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9304886638",
			},
			pants = {
				"rbxassetid://9304886812",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9304904845",
			},
			pants = {
				"rbxassetid://9304905025",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#1638AD"),
		auxillary = Color3.fromHex("#FFB81C"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.COL = {
	name = "Colorado Avalanche",
	abbreviation = "COL",
	logo = "rbxassetid://474184892",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9307626227",
			},
			pants = {
				"rbxassetid://9307626314",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9314546781",
			},
			pants = {
				"rbxassetid://9307630399",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#632A3B"),
		auxillary = Color3.fromHex("#18517c"),
		tertiary = Color3.fromHex("#A2AAAD"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.BOS = {
	name = "Boston Bruins",
	abbreviation = "BOS",
	logo = "rbxassetid://472762334",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9304628018",
			},
			pants = {
				"rbxassetid://9304628210",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9304642444",
			},
			pants = {
				"rbxassetid://9304642650",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#FFB81C"),
		auxillary = Color3.fromHex("#000000"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.CGY = {
	name = "Calgary Flames",
	abbreviation = "CGY",
	logo = "rbxassetid://472765508",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9305171730",
			},
			pants = {
				"rbxassetid://9305171981",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9305182192",
			},
			pants = {
				"rbxassetid://9305182500",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#D2001C"),
		auxillary = Color3.fromHex("#FAAF19"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.CAR = {
	name = "Carolina Hurricanes",
	abbreviation = "CAR",
	logo = "rbxassetid://472767535",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9306054760",
			},
			pants = {
				"rbxassetid://9306054914",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9306063268",
			},
			pants = {
				"rbxassetid://9306063593",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#CE1126"),
		auxillary = Color3.fromHex("#ffffff"),
		tertiary = Color3.fromHex("#000000"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.CHI = {
	name = "Chicago Blackhawks",
	abbreviation = "CHI",
	logo = "rbxassetid://474152901",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9307657896",
			},
			pants = {
				"rbxassetid://9306185936",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9306190126",
			},
			pants = {
				"rbxassetid://9306190210",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#CF0A2C"),
		auxillary = Color3.fromHex("#000000"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.CBJ = {
	name = "Columbus Blue Jackets",
	abbreviation = "CBJ",
	logo = "rbxassetid://474185562",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9392126213",
			},
			pants = {
				"rbxassetid://9392126368",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9392255420",
			},
			pants = {
				"rbxassetid://9392255564",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#002654"),
		auxillary = Color3.fromHex("#ce1126"),
		tertiary = Color3.fromHex("#A4A9AD"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.EDM = {
	name = "Edmonton Oilers",
	abbreviation = "EDM",
	logo = "rbxassetid://474186927",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9392315879",
			},
			pants = {
				"rbxassetid://9392316088",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9392322378",
			},
			pants = {
				"rbxassetid://9392322578",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#041E42"),
		auxillary = Color3.fromHex("#FF4C00"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.FLA = {
	name = "Florida Panthers",
	abbreviation = "FLA",
	logo = "rbxassetid://8240678590",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9392338429",
			},
			pants = {
				"rbxassetid://9392338692",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9392347462",
			},
			pants = {
				"rbxassetid://9392347614",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#041E42"),
		auxillary = Color3.fromHex("#c8102E"),
		tertiary = Color3.fromHex("#B9975B"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.MIN = {
	name = "Minnesota Wild",
	abbreviation = "MIN",
	logo = "rbxassetid://474188937",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432134287",
			},
			pants = {
				"rbxassetid://9432134379",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432135809",
			},
			pants = {
				"rbxassetid://9432136068",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#154734"),
		auxillary = Color3.fromHex("#A6192E"),
		tertiary = Color3.fromHex("#EAAA00"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.NSH = {
	name = "Nashville Predators",
	abbreviation = "NSH",
	logo = "rbxassetid://474189990",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432159077",
			},
			pants = {
				"rbxassetid://9432159217",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432160591",
			},
			pants = {
				"rbxassetid://9432160697",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#FFB81C"),
		auxillary = Color3.fromHex("#041E42"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.NJD = {
	name = "New Jersey Devils",
	abbreviation = "NJD",
	logo = "rbxassetid://474190469",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432173969",
			},
			pants = {
				"rbxassetid://9432174129",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432176697",
			},
			pants = {
				"rbxassetid://9432176879",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#CE1126"),
		auxillary = Color3.fromHex("#000000"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.NYI = {
	name = "New York Islanders",
	abbreviation = "NYI",
	logo = "rbxassetid://474191640",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432187172",
			},
			pants = {
				"rbxassetid://9432187314",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432189318",
			},
			pants = {
				"rbxassetid://9432189555",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#00539b"),
		auxillary = Color3.fromHex("#f47d30"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.NYR = {
	name = "New York Rangers",
	abbreviation = "NYR",
	logo = "rbxassetid://474195048",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432200847",
			},
			pants = {
				"rbxassetid://9432200985",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432203012",
			},
			pants = {
				"rbxassetid://9432203106",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#0038A8"),
		auxillary = Color3.fromHex("#CE1126"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.OTT = {
	name = "Ottawa Senators",
	abbreviation = "OTT",
	logo = "rbxassetid://474195459",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9476701909",
			},
			pants = {
				"rbxassetid://9432213601",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432215303",
			},
			pants = {
				"rbxassetid://9432215446",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#c52032"),
		auxillary = Color3.fromHex("#C2912C"),
		tertiary = Color3.fromHex("#000000"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.PHI = {
	name = "Philadelphia Flyers",
	abbreviation = "PHI",
	logo = "rbxassetid://474195835",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432223213",
			},
			pants = {
				"rbxassetid://9432223384",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432224735",
			},
			pants = {
				"rbxassetid://9432225125",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#F74902"),
		auxillary = Color3.fromHex("#000000"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.PIT = {
	name = "Pittsburgh Penguins",
	abbreviation = "PIT",
	logo = "rbxassetid://474198251",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432236027",
			},
			pants = {
				"rbxassetid://9432236139",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432237754",
			},
			pants = {
				"rbxassetid://9432237844",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#000000"),
		auxillary = Color3.fromHex("#FCB514"),
		tertiary = Color3.fromHex("#CFC493"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.STL = {
	name = "St. Louis Blues",
	abbreviation = "STL",
	logo = "rbxassetid://474197375",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432279724",
			},
			pants = {
				"rbxassetid://9432279981",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9476703486",
			},
			pants = {
				"rbxassetid://9432316229",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#041E42"),
		auxillary = Color3.fromHex("#FCB514"),
		tertiary = Color3.fromHex("#002F87"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.SEA = {
	name = "Seattle Kraken",
	abbreviation = "SEA",
	logo = "rbxassetid://0",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432266600",
			},
			pants = {
				"rbxassetid://9432266736",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432270596",
			},
			pants = {
				"rbxassetid://9432270842",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#99d9dd"),
		auxillary = Color3.fromHex("#001628"),
		tertiary = Color3.fromHex("#68a2b9"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.TBL = {
	name = "Tampa Bay Lightning",
	abbreviation = "TBL",
	logo = "rbxassetid://410870343",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432337977",
			},
			pants = {
				"rbxassetid://9432338176",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432339962",
			},
			pants = {
				"rbxassetid://9432340186",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#002868"),
		auxillary = Color3.fromHex("#ffffff"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.VAN = {
	name = "Vancouver Canucks",
	abbreviation = "VAN",
	logo = "rbxassetid://474200012",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432371175",
			},
			pants = {
				"rbxassetid://9432371329",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432373191",
			},
			pants = {
				"rbxassetid://9432373362",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#00205B"),
		auxillary = Color3.fromHex("#00843d"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.VGK = {
	name = "Vegas Golden Knights",
	abbreviation = "VGK",
	logo = "rbxassetid://553987509",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432375664",
			},
			pants = {
				"rbxassetid://9432376401",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432377242",
			},
			pants = {
				"rbxassetid://9432378120",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#B4975A"),
		auxillary = Color3.fromHex("#333f42"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.WSH = {
	name = "Washington Capitals",
	abbreviation = "WSH",
	logo = "rbxassetid://474200462",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432381401",
			},
			pants = {
				"rbxassetid://9476691796",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432382627",
			},
			pants = {
				"rbxassetid://9432382863",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#041E42"),
		auxillary = Color3.fromHex("#C8102E"),
		tertiary = Color3.fromHex("#ffffff"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

nhl_teams.WPG = {
	name = "Winnipeg Jets",
	abbreviation = "WPG",
	logo = "rbxassetid://474201029",

	uniforms = {
		home = {
			jersey = {
				"rbxassetid://9432386334",
			},
			pants = {
				"rbxassetid://9432386458",
			},
		},

		away = {
			jersey = {
				"rbxassetid://9432396952",
			},
			pants = {
				"rbxassetid://9432397074",
			},
		},
	},

	colors = {
		primary = Color3.fromHex("#041E42"),
		auxillary = Color3.fromHex("#AC162C"),
		tertiary = Color3.fromHex("#004C97"),
	},

	horn = {
		sound = "rbxassetid://5818699832",
		volume = 1,
		time_position = 1,
	},
}

return nhl_teams
